// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8FVsklaJDd2q7TvTZ-i4ufy4E_JeKtWs',
    appId: '1:871004286975:web:83faa9e27025cab3eb41ca',
    messagingSenderId: '871004286975',
    projectId: 'test-project-811c3',
    authDomain: 'test-project-811c3.firebaseapp.com',
    storageBucket: 'test-project-811c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB655qRIR9OfkQldAAGbMpoWKNuIjXypeM',
    appId: '1:871004286975:android:20980f571b51272beb41ca',
    messagingSenderId: '871004286975',
    projectId: 'test-project-811c3',
    storageBucket: 'test-project-811c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdW1OIV2fx9omrvpUhIUhj1_giLcekbkM',
    appId: '1:871004286975:ios:74f2edb9a640e6eaeb41ca',
    messagingSenderId: '871004286975',
    projectId: 'test-project-811c3',
    storageBucket: 'test-project-811c3.firebasestorage.app',
    iosClientId:
        '871004286975-ban34niv0tph8gju20g15ak4cssu898i.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdW1OIV2fx9omrvpUhIUhj1_giLcekbkM',
    appId: '1:871004286975:ios:74f2edb9a640e6eaeb41ca',
    messagingSenderId: '871004286975',
    projectId: 'test-project-811c3',
    storageBucket: 'test-project-811c3.firebasestorage.app',
    iosClientId:
        '871004286975-ban34niv0tph8gju20g15ak4cssu898i.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPure',
  );
}
